// ============================================================
// BK TRAINING MANAGEMENT DATA MODEL
// data.js — initial dataset (replace via Import Data module)
// ============================================================

window.BKData = {
  meta: {
    tahun: 2026,
    bahagian: "Bahagian Kurikulum",
    jabatan: "Jabatan Pendidikan Politeknik dan Kolej Komuniti (JPPKK)",
    versi: "1.0.0",
    tarikhMuat: new Date().toISOString(),
    sumberData: "Data awal sistem — import Excel untuk menggantikan",
  },

  // ─── STATUS ENUMS ─────────────────────────────────────────
  STATUS_LATIHAN: [
    "Draft",
    "Dalam Perancangan",
    "Menunggu Kelulusan",
    "Diluluskan",
    "Dalam Pelaksanaan",
    "Telah Dilaksanakan",
    "Ditangguhkan",
    "Dibatalkan",
  ],
  STATUS_KEWANGAN: [
    "Belum Ada Peruntukan",
    "Menunggu Subwaran",
    "Peruntukan Diluluskan",
    "Dalam Proses Pembayaran",
    "Pembayaran Selesai",
    "Lebihan Dikembalikan",
  ],
  STATUS_LAPORAN: ["Belum Disediakan", "Dalam Penyediaan", "Menunggu Semakan", "Menunggu Kelulusan", "Diluluskan", "Lengkap"],
  KAEDAH: ["Bersemuka", "Dalam Talian", "Hibrid", "Lawatan Industri", "Bengkel", "Seminar", "Kursus Luaran", "e-Pembelajaran"],
  SUMBER_PERUNTUKAN: ["Peruntukan Mengurus JPPKK", "Peruntukan Pembangunan", "Sumber Luar", "Yuran Peserta", "Tiada Peruntukan"],
  UNIT: [
    "Bahagian Kurikulum",
    "Unit Pengurusan Kurikulum",
    "Unit Pembangunan Program",
    "Unit Jaminan Kualiti",
    "Unit Inovasi & Teknologi",
    "Unit Penyelidikan & Pembangunan",
    "Unit Pengurusan Am",
    "Lain-lain",
  ],

  // ─── LATIHAN RECORDS ──────────────────────────────────────
  latihan: [
    {
      id: "LAT-2026-001",
      bil: 1,
      tajuk: "Bengkel Pembangunan Kurikulum TVET 2026",
      unit: "Unit Pembangunan Program",
      koordinator: "Pn. Siti Aminah",
      kaedah: "Bersemuka",
      tempat: "Bilik Mesyuarat Utama, JPPKK",
      tempatOnline: null,
      // Cadangan
      cad_mula: "2026-02-10",
      cad_tamat: "2026-02-12",
      bilHari: 3,
      // Semak / pengesahan jadual
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      // Pelaksanaan sebenar
      sebenar_mula: null,
      sebenar_tamat: null,
      // Peserta
      sasaranPeserta: 40,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      // Status
      statusLatihan: "Diluluskan",
      statusKelulusan: "Diluluskan",
      statusKewangan: "Peruntukan Diluluskan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Menunggu Pelaksanaan",
      // Kewangan
      anggaranPerbelanjaan: 8500,
      silingPeruntukan: 10000,
      peruntutkanDiluluskan: 8500,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 8500,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: "SW-2026-0012",
      subwaranDisahkan: true,
      poNo: null,
      statusInvois: "Belum Diterima",
      tarikhBayar: null,
      catatanKewangan: null,
      // Objektif
      objektif: "Membangun dan mengkaji semula kurikulum TVET mengikut keperluan industri semasa.",
      kumpulanSasaran: "Pensyarah dan Penyelaras Kurikulum Politeknik & Kolej Komuniti",
      kategorLatihan: "Pembangunan Profesional",
      penganjur: "Bahagian Kurikulum, JPPKK",
      penceramah: "Prof. Madya Dr. Razali bin Hassan",
      // Dokumen
      kertasKerja: { status: "Diluluskan", tarikhDihantar: "2025-12-15" },
      kelulusan: { no: "KEL-BK-2026-001", tarikh: "2026-01-10", oleh: "Pengarah Bahagian Kurikulum" },
      // Semak & audit
      catatan: "Bengkel dua fasa — modul disahkan oleh bahagian industri.",
      dataLengkap: false,
      flagMissing: ["sebenar_mula", "sebenar_tamat", "kehadiranSebenar", "perbelanjaanSebenar"],
      auditTrail: [
        { tarikh: "2025-11-20", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
        { tarikh: "2025-12-15", pengguna: "TC", tindakan: "Kertas kerja dihantar", perubahan: {} },
        { tarikh: "2026-01-10", pengguna: "Ketua Unit", tindakan: "Kelulusan diberikan", perubahan: { statusKelulusan: ["Menunggu Kelulusan", "Diluluskan"] } },
      ],
    },
    {
      id: "LAT-2026-002",
      bil: 2,
      tajuk: "Kursus Penilaian dan Pentaksiran Berdasarkan Kompetensi",
      unit: "Unit Jaminan Kualiti",
      koordinator: "En. Mohd Fadzli",
      kaedah: "Hibrid",
      tempat: "Bilik Latihan 3, Aras 2",
      tempatOnline: "Zoom",
      cad_mula: "2026-03-03",
      cad_tamat: "2026-03-05",
      bilHari: 3,
      jadualDisemak: true,
      jadualBaru_mula: "2026-03-10",
      jadualBaru_tamat: "2026-03-12",
      sebabPerubahanJadual: "Pertembungan dengan Program Khas Bahagian pada 3-5 Mac 2026",
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 60,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Diluluskan",
      statusKelulusan: "Diluluskan",
      statusKewangan: "Menunggu Subwaran",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Menunggu Pelaksanaan",
      anggaranPerbelanjaan: 12000,
      silingPeruntukan: 15000,
      peruntutkanDiluluskan: 12000,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Diterima",
      tarikhBayar: null,
      catatanKewangan: "Subwaran masih belum diterima dari Bahagian Kewangan.",
      objektif: "Meningkatkan keupayaan pensyarah dalam penilaian berasaskan kompetensi.",
      kumpulanSasaran: "Pensyarah Politeknik",
      kategorLatihan: "Pedagogi & Pentaksiran",
      penganjur: "Unit Jaminan Kualiti, BK",
      penceramah: "Dr. Noraini bt Jaafar",
      kertasKerja: { status: "Diluluskan", tarikhDihantar: "2026-01-08" },
      kelulusan: { no: "KEL-BK-2026-002", tarikh: "2026-01-22", oleh: "Pengarah Bahagian Kurikulum" },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["subwaranNo", "sebenar_mula", "sebenar_tamat", "kehadiranSebenar", "perbelanjaanSebenar"],
      auditTrail: [
        { tarikh: "2025-12-10", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-003",
      bil: 3,
      tajuk: "Program Pemantapan Daya Saing Pensyarah: Industri 4.0 & Kemahiran Digital",
      unit: "Unit Inovasi & Teknologi",
      koordinator: "Pn. Hasniza Zainal",
      kaedah: "Bersemuka",
      tempat: "Dewan Seminar, JPPKK KL",
      tempatOnline: null,
      cad_mula: "2026-04-07",
      cad_tamat: "2026-04-09",
      bilHari: 3,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 80,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Menunggu Kelulusan",
      statusKelulusan: "Menunggu Kelulusan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 18000,
      silingPeruntukan: 20000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Mendedahkan pensyarah kepada teknologi Industri 4.0 dan memperkukuh kemahiran digital.",
      kumpulanSasaran: "Ketua Jabatan dan Pensyarah Senior",
      kategorLatihan: "Teknologi & Inovasi",
      penganjur: "Unit Inovasi & Teknologi, BK",
      penceramah: "TBC",
      kertasKerja: { status: "Menunggu Kelulusan", tarikhDihantar: "2026-02-01" },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: "Kertas kerja dikemukakan — menunggu kelulusan Pengarah.",
      dataLengkap: false,
      flagMissing: ["peruntutkanDiluluskan", "kelulusan", "penceramah", "sebenar_mula", "sebenar_tamat"],
      auditTrail: [
        { tarikh: "2026-01-20", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
        { tarikh: "2026-02-01", pengguna: "TC", tindakan: "Kertas kerja dikemukakan untuk kelulusan", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-004",
      bil: 4,
      tajuk: "Bengkel Analisis Keperluan Latihan (TNA) Bahagian Kurikulum 2026",
      unit: "Bahagian Kurikulum",
      koordinator: "Pn. Siti Aminah",
      kaedah: "Bersemuka",
      tempat: "Bilik Mesyuarat BK 2",
      tempatOnline: null,
      cad_mula: "2026-01-20",
      cad_tamat: "2026-01-21",
      bilHari: 2,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: "2026-01-20",
      sebenar_tamat: "2026-01-21",
      sasaranPeserta: 25,
      kehadiranSebenar: 23,
      kehadiranDisahkan: true,
      statusLatihan: "Telah Dilaksanakan",
      statusKelulusan: "Diluluskan",
      statusKewangan: "Pembayaran Selesai",
      statusLaporan: "Dalam Penyediaan",
      statusPelaksanaan: "Selesai",
      anggaranPerbelanjaan: 4200,
      silingPeruntukan: 5000,
      peruntutkanDiluluskan: 4200,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 4200,
      perbelanjaanSebenar: 3950,
      baki: 250,
      subwaranNo: "SW-2026-0003",
      subwaranDisahkan: true,
      poNo: "PO-2026-0041",
      statusInvois: "Dibayar",
      tarikhBayar: "2026-02-10",
      catatanKewangan: "Baki RM250 — caj penceramah lebih rendah dari anggaran.",
      objektif: "Mengenal pasti keperluan latihan tahunan staf BK dan menentukan keutamaan program 2026.",
      kumpulanSasaran: "Semua pegawai Bahagian Kurikulum",
      kategorLatihan: "Pengurusan & Perancangan",
      penganjur: "Bahagian Kurikulum, JPPKK",
      penceramah: "Pn. Rahayu bt Ahmad (Pakar TNA)",
      kertasKerja: { status: "Diluluskan", tarikhDihantar: "2025-12-20" },
      kelulusan: { no: "KEL-BK-2026-000", tarikh: "2026-01-05", oleh: "Pengarah Bahagian Kurikulum" },
      catatan: "Laporan sedang disediakan. Dapatan TNA akan digunakan untuk Pelan Latihan BK 2027.",
      dataLengkap: false,
      flagMissing: ["statusLaporan"],
      auditTrail: [
        { tarikh: "2025-12-18", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
        { tarikh: "2026-01-21", pengguna: "TC", tindakan: "Pelaksanaan selesai, kehadiran dikemas kini", perubahan: {} },
        { tarikh: "2026-02-10", pengguna: "Pn. Hasniza", tindakan: "Status pembayaran dikemas kini", perubahan: { perbelanjaanSebenar: [null, 3950] } },
      ],
    },
    {
      id: "LAT-2026-005",
      bil: 5,
      tajuk: "Seminar Penyelidikan Tindakan (Action Research) dalam Pendidikan TVET",
      unit: "Unit Penyelidikan & Pembangunan",
      koordinator: "En. Zulkifli Ismail",
      kaedah: "Bersemuka",
      tempat: "Dewan Kuliah A, JPPKK",
      tempatOnline: null,
      cad_mula: "2026-05-19",
      cad_tamat: "2026-05-20",
      bilHari: 2,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 50,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Dalam Perancangan",
      statusKelulusan: "Dalam Perancangan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 9500,
      silingPeruntukan: 12000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Mendedahkan pensyarah kepada metodologi penyelidikan tindakan sebagai alat peningkatan amalan pengajaran.",
      kumpulanSasaran: "Pensyarah Politeknik dan Kolej Komuniti yang berminat dalam penyelidikan",
      kategorLatihan: "Penyelidikan & Inovasi",
      penganjur: "Unit Penyelidikan & Pembangunan, BK",
      penceramah: "Prof. Dr. Siti Rahimah bt Zakaria (UTM)",
      kertasKerja: { status: "Draft", tarikhDihantar: null },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: "Kertas kerja sedang disediakan.",
      dataLengkap: false,
      flagMissing: ["kertasKerja_submitted", "kelulusan", "peruntutkanDiluluskan"],
      auditTrail: [
        { tarikh: "2026-02-05", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-006",
      bil: 6,
      tajuk: "Kursus Reka Bentuk Instruksional dan e-Konten TVET",
      unit: "Unit Inovasi & Teknologi",
      koordinator: "Pn. Hasniza Zainal",
      kaedah: "Dalam Talian",
      tempat: null,
      tempatOnline: "Microsoft Teams",
      cad_mula: "2026-06-08",
      cad_tamat: "2026-06-10",
      bilHari: 3,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 70,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Dalam Perancangan",
      statusKelulusan: "Dalam Perancangan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 6000,
      silingPeruntukan: 8000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Meningkatkan kemahiran pensyarah dalam reka bentuk pembelajaran dalam talian.",
      kumpulanSasaran: "Pensyarah dari semua politeknik dan kolej komuniti",
      kategorLatihan: "Teknologi & Inovasi",
      penganjur: "Unit Inovasi & Teknologi, BK",
      penceramah: "Pakar e-Pembelajaran dalaman",
      kertasKerja: { status: "Draft", tarikhDihantar: null },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["tempat", "kertasKerja_submitted", "kelulusan"],
      auditTrail: [
        { tarikh: "2026-02-10", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-007",
      bil: 7,
      tajuk: "Bengkel Pengukuhan Pengurusan Pentadbiran Urus Setia",
      unit: "Unit Pengurusan Am",
      koordinator: "Cik Nursyahidah Ramlan",
      kaedah: "Bersemuka",
      tempat: "Bilik Latihan 1",
      tempatOnline: null,
      cad_mula: "2026-07-14",
      cad_tamat: "2026-07-15",
      bilHari: 2,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 30,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Dalam Perancangan",
      statusKelulusan: "Dalam Perancangan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 5500,
      silingPeruntukan: 6000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Meningkatkan kecekapan urusan pentadbiran dan urus setia.",
      kumpulanSasaran: "Pembantu Tadbir dan Pegawai Tadbir BK",
      kategorLatihan: "Pengurusan & Pentadbiran",
      penganjur: "Unit Pengurusan Am, BK",
      penceramah: "Pegawai Tadbir Kanan JPPKK",
      kertasKerja: { status: "Belum Disediakan", tarikhDihantar: null },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["kertasKerja", "kelulusan", "peruntutkanDiluluskan"],
      auditTrail: [
        { tarikh: "2026-02-15", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-008",
      bil: 8,
      tajuk: "Program Lawatan Industri: Amalan Terbaik Latihan Vokasional Antarabangsa",
      unit: "Unit Pengurusan Kurikulum",
      koordinator: "En. Mohd Fadzli",
      kaedah: "Lawatan Industri",
      tempat: "Korea Selatan / Jerman (TBC)",
      tempatOnline: null,
      cad_mula: "2026-09-07",
      cad_tamat: "2026-09-13",
      bilHari: 7,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 10,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Menunggu Kelulusan",
      statusKelulusan: "Menunggu Kelulusan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 45000,
      silingPeruntukan: 50000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Pembangunan",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: "Program bergantung kepada kelulusan peruntukan pembangunan.",
      objektif: "Mendedahkan pegawai kepada amalan terbaik latihan TVET peringkat antarabangsa.",
      kumpulanSasaran: "Pegawai Kanan Bahagian Kurikulum",
      kategorLatihan: "Pembangunan Profesional",
      penganjur: "Unit Pengurusan Kurikulum, BK",
      penceramah: "Institusi teknikal luar negara (TBC)",
      kertasKerja: { status: "Menunggu Kelulusan", tarikhDihantar: "2026-02-20" },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: "Kelulusan program dan peruntukan diperlukan sebelum pengesahan tempat.",
      dataLengkap: false,
      flagMissing: ["kelulusan", "peruntutkanDiluluskan", "tempat_konfirm"],
      auditTrail: [
        { tarikh: "2026-01-30", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
        { tarikh: "2026-02-20", pengguna: "TC", tindakan: "Kertas kerja dikemukakan", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-009",
      bil: 9,
      tajuk: "Kursus Kepimpinan dan Pengurusan Strategik untuk Pegawai Pertengahan",
      unit: "Bahagian Kurikulum",
      koordinator: "Pn. Siti Aminah",
      kaedah: "Bersemuka",
      tempat: "Hotel (TBC)",
      tempatOnline: null,
      cad_mula: "2026-10-13",
      cad_tamat: "2026-10-15",
      bilHari: 3,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 35,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Dalam Perancangan",
      statusKelulusan: "Dalam Perancangan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 22000,
      silingPeruntukan: 25000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Memperkukuhkan keupayaan kepimpinan dan pengurusan dalam kalangan pegawai pertengahan.",
      kumpulanSasaran: "Pegawai Pertengahan (Gred 44-52), BK",
      kategorLatihan: "Kepimpinan & Pengurusan",
      penganjur: "Bahagian Kurikulum, JPPKK",
      penceramah: "Institut Tadbiran Awam Negara (INTAN)",
      kertasKerja: { status: "Belum Disediakan", tarikhDihantar: null },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["kertasKerja", "kelulusan", "tempat_konfirm", "peruntutkanDiluluskan"],
      auditTrail: [
        { tarikh: "2026-02-15", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-010",
      bil: 10,
      tajuk: "Bengkel Penambahbaikan Berterusan (CQI) Kurikulum TVET",
      unit: "Unit Jaminan Kualiti",
      koordinator: "En. Mohd Fadzli",
      kaedah: "Bersemuka",
      tempat: "Bilik Mesyuarat BK 1",
      tempatOnline: null,
      cad_mula: "2026-11-10",
      cad_tamat: "2026-11-11",
      bilHari: 2,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 45,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Dalam Perancangan",
      statusKelulusan: "Dalam Perancangan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 7000,
      silingPeruntukan: 8000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Mengenal pasti peluang CQI dalam perancangan dan pelaksanaan kurikulum TVET.",
      kumpulanSasaran: "Penyelaras Program dan Pensyarah Senior",
      kategorLatihan: "Jaminan Kualiti",
      penganjur: "Unit Jaminan Kualiti, BK",
      penceramah: "Pegawai JK Dalaman",
      kertasKerja: { status: "Belum Disediakan", tarikhDihantar: null },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["kertasKerja", "kelulusan", "peruntutkanDiluluskan"],
      auditTrail: [
        { tarikh: "2026-02-20", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-011",
      bil: 11,
      tajuk: "Kursus Bahasa Inggeris untuk Tujuan Profesional (Pensyarah)",
      unit: "Unit Pengurusan Kurikulum",
      koordinator: "Cik Nursyahidah Ramlan",
      kaedah: "Hibrid",
      tempat: "Makmal Bahasa, JPPKK",
      tempatOnline: "Zoom",
      cad_mula: "2026-08-03",
      cad_tamat: "2026-08-07",
      bilHari: 5,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 30,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Dalam Perancangan",
      statusKelulusan: "Dalam Perancangan",
      statusKewangan: "Belum Ada Peruntukan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Dalam Perancangan",
      anggaranPerbelanjaan: 11000,
      silingPeruntukan: 12000,
      peruntutkanDiluluskan: null,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 0,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: null,
      subwaranDisahkan: false,
      poNo: null,
      statusInvois: "Belum Berkaitan",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Meningkatkan kemahiran komunikasi Bahasa Inggeris pensyarah untuk tujuan akademik dan profesional.",
      kumpulanSasaran: "Pensyarah Politeknik dan Kolej Komuniti",
      kategorLatihan: "Pembangunan Bahasa",
      penganjur: "Unit Pengurusan Kurikulum, BK",
      penceramah: "Perunding bahasa berdaftar",
      kertasKerja: { status: "Draft", tarikhDihantar: null },
      kelulusan: { no: null, tarikh: null, oleh: null },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["kertasKerja_submitted", "kelulusan", "peruntutkanDiluluskan"],
      auditTrail: [
        { tarikh: "2026-02-12", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
      ],
    },
    {
      id: "LAT-2026-012",
      bil: 12,
      tajuk: "Program Orientasi Pegawai Baharu Bahagian Kurikulum",
      unit: "Bahagian Kurikulum",
      koordinator: "Pn. Siti Aminah",
      kaedah: "Bersemuka",
      tempat: "Bilik Latihan 2",
      tempatOnline: null,
      cad_mula: "2026-03-16",
      cad_tamat: "2026-03-17",
      bilHari: 2,
      jadualDisemak: false,
      jadualBaru_mula: null,
      jadualBaru_tamat: null,
      sebabPerubahanJadual: null,
      sebenar_mula: null,
      sebenar_tamat: null,
      sasaranPeserta: 8,
      kehadiranSebenar: null,
      kehadiranDisahkan: false,
      statusLatihan: "Diluluskan",
      statusKelulusan: "Diluluskan",
      statusKewangan: "Peruntukan Diluluskan",
      statusLaporan: "Belum Disediakan",
      statusPelaksanaan: "Menunggu Pelaksanaan",
      anggaranPerbelanjaan: 2500,
      silingPeruntukan: 3000,
      peruntutkanDiluluskan: 2500,
      sumberPeruntukan: "Peruntukan Mengurus JPPKK",
      komitmenKewangan: 2500,
      perbelanjaanSebenar: null,
      baki: null,
      subwaranNo: "SW-2026-0021",
      subwaranDisahkan: true,
      poNo: null,
      statusInvois: "Belum Diterima",
      tarikhBayar: null,
      catatanKewangan: null,
      objektif: "Memberi pendedahan awal kepada pegawai baharu tentang tugas, struktur dan budaya kerja BK.",
      kumpulanSasaran: "Pegawai baharu BK 2026",
      kategorLatihan: "Induksi & Orientasi",
      penganjur: "Bahagian Kurikulum, JPPKK",
      penceramah: "Ketua-ketua Unit BK",
      kertasKerja: { status: "Diluluskan", tarikhDihantar: "2026-01-25" },
      kelulusan: { no: "KEL-BK-2026-003", tarikh: "2026-02-05", oleh: "Pengarah Bahagian Kurikulum" },
      catatan: null,
      dataLengkap: false,
      flagMissing: ["sebenar_mula", "sebenar_tamat", "kehadiranSebenar", "perbelanjaanSebenar"],
      auditTrail: [
        { tarikh: "2026-01-22", pengguna: "TC", tindakan: "Rekod dicipta", perubahan: {} },
        { tarikh: "2026-02-05", pengguna: "Ketua Unit", tindakan: "Kelulusan diberikan", perubahan: {} },
      ],
    },
  ],

  // ─── PESERTA (Participant records) ───────────────────────
  peserta: [],

  // ─── PENILAIAN (Evaluation records) ──────────────────────
  penilaian: [
    {
      id: "EVAL-004",
      latihanId: "LAT-2026-004",
      tarikhPenilaian: "2026-01-21",
      bilResponden: 22,
      kepuasanPeserta: 4.2,
      relevansKandungan: 4.4,
      keberkesananPenceramah: 4.5,
      pencapaianObjektif: 4.1,
      peningkatanIlmu: 4.3,
      ulasan: "Bengkel sangat berguna dan praktikal. Peserta meminta sesi lanjutan.",
      cadangan: "Perlu ada modul susulan untuk memantau pelaksanaan TNA.",
      cqiDikenal: true,
    },
  ],

  // ─── CQI ACTIONS ──────────────────────────────────────────
  cqiActions: [
    {
      id: "CQI-2026-001",
      latihanId: "LAT-2026-004",
      dapatan: "Bengkel TNA tidak disusuli dengan sesi pemantauan pelaksanaan cadangan.",
      punca: "Tiada mekanisme susulan ditetapkan dalam kertas kerja asal.",
      tindakan: "Sediakan templat pelan tindakan TNA dan jadual pemantauan berkala.",
      pegawaiBertanggungjawab: "Pn. Siti Aminah",
      tarikhSasaran: "2026-04-30",
      statusTindakan: "Dalam Proses",
      buktiPenyelesaian: null,
      semakKeberkesanan: null,
    },
  ],

  // ─── DOKUMEN ──────────────────────────────────────────────
  dokumen: [],

  // ─── TINDAKAN SUSULAN ─────────────────────────────────────
  tindakanSusulan: [
    {
      id: "ACT-2026-001",
      jenis: "Menunggu Kelulusan",
      tajuk: "Kelulusan Kertas Kerja LAT-2026-003 masih belum diterima",
      latihanId: "LAT-2026-003",
      pegawai: "Pn. Siti Aminah",
      tarikhDue: "2026-03-15",
      prioriti: "Tinggi",
      status: "Terbuka",
      catatan: "Kertas kerja dikemukakan 1 Feb 2026.",
    },
    {
      id: "ACT-2026-002",
      jenis: "Menunggu Subwaran",
      tajuk: "Subwaran LAT-2026-002 belum diterima",
      latihanId: "LAT-2026-002",
      pegawai: "En. Mohd Fadzli",
      tarikhDue: "2026-03-01",
      prioriti: "Tinggi",
      status: "Terbuka",
      catatan: "Diajukan kepada Bahagian Kewangan 20 Jan 2026.",
    },
    {
      id: "ACT-2026-003",
      jenis: "Laporan Belum Disediakan",
      tajuk: "Laporan latihan LAT-2026-004 sedang disediakan",
      latihanId: "LAT-2026-004",
      pegawai: "Pn. Siti Aminah",
      tarikhDue: "2026-03-05",
      prioriti: "Sederhana",
      status: "Dalam Proses",
      catatan: null,
    },
    {
      id: "ACT-2026-004",
      jenis: "Menunggu Kelulusan",
      tajuk: "Kelulusan Kertas Kerja LAT-2026-008 masih belum diterima",
      latihanId: "LAT-2026-008",
      pegawai: "En. Mohd Fadzli",
      tarikhDue: "2026-04-01",
      prioriti: "Tinggi",
      status: "Terbuka",
      catatan: "Program mahal — memerlukan kelulusan Ketua Setiausaha.",
    },
  ],

  // ─── TETAPAN SISTEM ────────────────────────────────────────
  tetapan: {
    namaOrganisasi: "Bahagian Kurikulum, JPPKK",
    tahunAktif: 2026,
    matawang: "RM",
    formatTarikh: "DD/MM/YYYY",
    penggunaSemasa: "Penyelaras Latihan",
    roleSemasa: "Koordinator",
    templatKertasKerja: null,
    logoOrg: null,
    notifikasiEmail: false,
    warnBudgetThreshold: 90,
    warnAttendanceThreshold: 80,
  },

  // ─── HELPER FUNCTIONS ──────────────────────────────────────
  getKPI() {
    const lat = this.latihan;
    const total = lat.length;
    const diluluskan = lat.filter((l) => l.statusKelulusan === "Diluluskan").length;
    const dilaksanakan = lat.filter((l) => l.statusLatihan === "Telah Dilaksanakan").length;
    const dalamPerancangan = lat.filter((l) => ["Dalam Perancangan", "Draft"].includes(l.statusLatihan)).length;
    const menungguKelulusan = lat.filter((l) => l.statusKelulusan === "Menunggu Kelulusan").length;
    const tangguhBatal = lat.filter((l) => ["Ditangguhkan", "Dibatalkan"].includes(l.statusLatihan)).length;
    const totalSasaran = lat.reduce((s, l) => s + (l.sasaranPeserta || 0), 0);
    const totalHadir = lat.reduce((s, l) => s + (l.kehadiranSebenar || 0), 0);
    const totalAnggar = lat.reduce((s, l) => s + (l.anggaranPerbelanjaan || 0), 0);
    const totalDiluluskan = lat.reduce((s, l) => s + (l.peruntutkanDiluluskan || 0), 0);
    const totalBelanja = lat.reduce((s, l) => s + (l.perbelanjaanSebenar || 0), 0);
    const baki = totalDiluluskan - totalBelanja;
    const laporanBelumLengkap = lat.filter((l) => l.statusLatihan === "Telah Dilaksanakan" && l.statusLaporan !== "Lengkap").length;
    return {
      total, diluluskan, dilaksanakan, dalamPerancangan,
      menungguKelulusan, tangguhBatal, totalSasaran, totalHadir,
      totalAnggar, totalDiluluskan, totalBelanja, baki, laporanBelumLengkap,
    };
  },

  nextId(prefix) {
    const existing = this.latihan.filter((l) => l.id.startsWith(prefix)).map((l) => parseInt(l.id.split("-").pop()));
    const max = existing.length ? Math.max(...existing) : 0;
    return `${prefix}-${String(max + 1).padStart(3, "0")}`;
  },

  formatRM(val) {
    if (val === null || val === undefined) return '<span class="text-muted">—</span>';
    return "RM " + Number(val).toLocaleString("ms-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  },

  formatDate(d) {
    if (!d) return '<span class="text-muted">—</span>';
    const dt = new Date(d);
    if (isNaN(dt)) return d;
    return dt.toLocaleDateString("ms-MY", { day: "2-digit", month: "2-digit", year: "numeric" });
  },

  statusClass(s) {
    const map = {
      "Draft": "status-draft",
      "Dalam Perancangan": "status-perancangan",
      "Menunggu Kelulusan": "status-menunggu",
      "Diluluskan": "status-diluluskan",
      "Dalam Pelaksanaan": "status-pelaksanaan",
      "Telah Dilaksanakan": "status-dilaksanakan",
      "Ditangguhkan": "status-ditangguhkan",
      "Dibatalkan": "status-dibatalkan",
      "Belum Disediakan": "status-belum",
      "Lengkap": "status-lengkap",
    };
    return map[s] || "status-draft";
  },
};
